# Generated by Django 3.2 on 2023-05-16 17:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatar'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.models.validate_timezone]),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_working_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
